# Generated by Django 4.2.3 on 2023-07-21 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('Technical Skill', 'Technical Skill'), ('Soft Skill', 'Soft Skill')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=100)),
                ('social_media_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperienceBulletPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bullet_point', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_url', models.URLField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('employment_start_date', models.DateTimeField(blank=True, null=True)),
                ('is_employed', models.BooleanField(default=False)),
                ('employment_end_date', models.DateTimeField(blank=True, null=True)),
                ('employment_duration', models.DurationField(blank=True, null=True)),
                ('bullet_points', models.ManyToManyField(blank=True, related_name='+', to='resumes.workexperiencebulletpoint')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_summary', models.TextField(blank=True)),
                ('certifications', models.ManyToManyField(blank=True, to='resumes.certification')),
                ('educations', models.ManyToManyField(blank=True, to='resumes.education')),
                ('personal_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.personalinformation')),
                ('work_experiences', models.ManyToManyField(blank=True, to='resumes.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resumeinformation')),
            ],
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='social_media_accounts',
            field=models.ManyToManyField(blank=True, to='resumes.socialmedia'),
        ),
    ]
