# Generated by Django 4.2.3 on 2023-07-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeinformation',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resumes.skill'),
        ),
    ]
